### ISSUE TITLE
Automatic positioning not working correctly

### ISSUE THREAD

**Issue by Willey1986** [lokesh-coder/toppy#30]
There seems to be an error with the `autoUpdate` property for `RelativePosition`.

When Placement is set to `OutsidePlacement.TOP_LEFT` but there is not enough space available, the placement seems to be set to `OutsidePlacement.TOP_RIGHT` but it should be ``OutsidePlacement.BOTTOM_LEFT``

**Placement OK**
![2019-03-11 15_32_38-Toppy - Overlay library for Angular](https://user-images.githubusercontent.com/1476579/54131736-3c679700-4413-11e9-806e-4b653f56d11d.png)

**Placement NOK - Tooltip should move to the bottom not to the right when not enough space available**
![2019-03-11 15_33_46-Toppy - Overlay library for Angular](https://user-images.githubusercontent.com/1476579/54131784-57d2a200-4413-11e9-9b2d-a0d8fa0232c4.png)

**Comment by lokesh-coder** [comment]
Hi @Willey1986,

Thanks for reporting the bug. Will fix that.

**Comment by Willey1986** [comment]
Hi @lokesh-coder.
Thank you for the quick response. Just to make sure, the same bug occurs for `OutsidePlacement.BOTTOM_LEFT` which gets resolved to BOTTOM_RIGHT. It seems like there is a general error in the calc() method.

**Comment by lokesh-coder** [comment]
True, I noticed the same. Right now the logic is build in a way to move adjacent corner. Let me fix that in calc().

**Comment by lokesh-coder** [comment]
Resolved and released new version v2.3.3 :tada:
