### ISSUE TITLE
Support overflow containers

### ISSUE THREAD

**Issue by ArielGueta** [lokesh-coder/toppy#34]
Thanks for the library. I am wondering if it has support for scrollable containers?

**Comment by lokesh-coder** [comment]
Hi @ArielGueta, what do you mean by scrollable containers?

**Comment by ArielGueta** [comment]
Hey, I mean element with overflow auto.

**Comment by lokesh-coder** [comment]
You can give height in config and inside the element you can have scrollbars.

Is that what you asked?

**Comment by ArielGueta** [comment]
Yes, thanks.
