### ISSUE TITLE
backdropClass does not seem to have effect?

### ISSUE THREAD

**Issue by mkontula** [lokesh-coder/toppy#35]
https://github.com/lokesh-coder/toppy/blob/5c34b127a320cbd3daa5539ff112a6080d634826/projects/toppy/src/lib/template.html#L1 looks like `t-backdrop` is fixed value and `config.backdropClass` is not used here.

**Comment by lokesh-coder** [comment]
Hey @mkontula , you are right. Will fix this today.

**Comment by lokesh-coder** [comment]
Fixed in v2.3.4  🎉

**Comment by mkontula** [comment]
Thanks for the lightning-fast-fix! Keep up the great job with this lib!
